/* Autogenerated, do not edit */
#ifndef __CR_VERSION_H__
#define __CR_VERSION_H__
#define CRIU_VERSION "3.14"
#define CRIU_VERSION_MAJOR  3
#define CRIU_VERSION_MINOR  14
#define CRIU_GITID "v3.14-126-g86b39805"
#endif /* __CR_VERSION_H__ */
